feat: testing with hysky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,18 +1,32 @@
 #!/usr/bin/env sh
 
-echo "[🐺 Husky]: Checking lint..."
+echo "[🐺 Husky][⏳ pre-commit]: Checking lint..."
 
-# Stage 1–4: ESLint
+# eslint
 npm run lint
 if [ $? -ne 0 ]; then
-  echo "[🐺 Husky]: 🚨 Oops! Lint failed!"
-  exit 1
+  echo "[🐺 Husky][🚨 pre-commit]: Oops! Lint failed!"
 fi
 
 # Check for secrets in code
-if grep -R "SECRET_KEY\|PASSWORD\|TOKEN" .; then
-  echo "[🐺 Husky]: 🚨 Found a secret in your code! Never commit secrets!"
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$' || true)
+SECRETS_FOUND=0
+
+for file in $STAGED_FILES; do
+  MATCHES=$(grep -En "(SECRET_KEY|PASSWORD|TOKEN|AWS_TOKEN)\s*=\s*['\"]" "$file" || true)
+
+  if [ -n "$MATCHES" ] || [ -n "$MATCHES_STRINGS" ]; then
+    echo "[🐺 Husky][🚨 pre-commit]: Found secret(s) in $file!"
+    [ -n "$MATCHES" ] && echo "$MATCHES"
+    [ -n "$MATCHES_STRINGS" ] && echo "$MATCHES_STRINGS"
+    SECRETS_FOUND=1
+  fi
+done
+
+if [ $SECRETS_FOUND -eq 1 ]; then
+  echo "[🐺 Husky][🚨 pre-commit]: Commit blocked! Fix secrets before committing!"
   exit 1
 fi
 
-echo "[🐺 Husky]: All checks passed! Ready to commit"
+echo "[🐺 Husky][✅ pre-commit]: All checks passed! Ready to commit"
+exit 0
